import { VisualSamplePreset, VoiceCommandPreset } from './types';
import kurtiProductImg from '../../assets/images/kurti_product_image_1788865143302.jpg';
import shirtProductImg from '../../assets/images/shirt_product_image_1788865161902.jpg';
import ethnicKurtiImg from '../../assets/images/ethnic_kurti_image_1788865173700.jpg';

export const TEXT_SEARCH_QUICK_CHIPS = [
  'Kurti pure cotton & embroidery',
  'Oxford cotton shirt fit & wash',
  'Battery life & drain',
  'Active noise cancellation',
  'Sensitive skin & redness',
  'Packaging arrived dented',
  'Fast 100W charging',
  'Waist sizing runs tight',
  'Zero white cast sunscreen',
  'Razor burn on neck',
  'Quiet cooling fans',
  'Authentic QR code verification',
  'Dual Zoom Air cushion',
];

export const VISUAL_SAMPLE_PRESETS: VisualSamplePreset[] = [
  {
    id: 'sample-kurti',
    label: 'Biba Pure Cotton Kurti',
    category: 'Fashion & Footwear',
    thumbnail: kurtiProductImg,
    description: 'Chikankari embroidered pastel cotton kurti tunic with side slits',
    targetProductQuery: 'Biba Women Embroidered Pure Cotton Straight Kurti embroidery fabric',
    detectedCues: ['Pure cotton kurti', 'Chikankari embroidery', 'Mandarin slit neckline', 'Ethnic tunic', 'Fashion & Footwear'],
  },
  {
    id: 'sample-shirt',
    label: 'Tommy Hilfiger Oxford Shirt',
    category: 'Fashion & Footwear',
    thumbnail: shirtProductImg,
    description: 'Light blue woven oxford cotton button-down long-sleeve casual shirt',
    targetProductQuery: 'Tommy Hilfiger Men Classic Oxford Cotton Casual Shirt fabric collar',
    detectedCues: ['Oxford cotton weave', 'Button-down collar', 'Barrel cuffs', 'Casual/Work shirt', 'Fashion & Footwear'],
  },
  {
    id: 'sample-ethnic-kurti',
    label: 'Libas Festive Anarkali Kurti',
    category: 'Fashion & Footwear',
    thumbnail: ethnicKurtiImg,
    description: 'Flared festive maroon and gold printed pure cotton Anarkali kurti',
    targetProductQuery: 'Libas Women Festive Floral Printed Anarkali Kurti print flare',
    detectedCues: ['Flared Anarkali cut', 'Gold foil botanical print', 'Pure cotton fabric', 'Festive ethnic wear'],
  },
  {
    id: 'sample-headphones',
    label: 'Sony WH-1000XM5 Headphones',
    category: 'Audio & Acoustics',
    thumbnail: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=400&q=80',
    description: 'Over-ear active noise-cancelling headphones in matte black finish',
    targetProductQuery: 'Sony WH-1000XM5 Headphones ANC sound battery',
    detectedCues: ['Over-ear headband', 'Active noise cancellation mic', 'Matte black earcups', 'Audio & Acoustics'],
  },
  {
    id: 'sample-serum',
    label: 'Minimalist Vitamin C Serum',
    category: 'Beauty & Skincare',
    thumbnail: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=400&q=80',
    description: 'Amber glass dropper bottle for dermatological skincare serum',
    targetProductQuery: 'Minimalist Vitamin C Serum skin brightening face',
    detectedCues: ['Glass dropper bottle', 'Topical skincare serum', 'Vitamin C active', 'Dermatology'],
  },
  {
    id: 'sample-phone',
    label: 'OnePlus 12 5G Smartphone',
    category: 'Smartphones & Mobile',
    thumbnail: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=400&q=80',
    description: 'Flagship smartphone back chassis with multi-lens camera module',
    targetProductQuery: 'OnePlus 12 5G smartphone camera display battery',
    detectedCues: ['Circular camera ring', 'Glass back panel', 'OLED display', 'Fast charging mobile'],
  },
  {
    id: 'sample-shoes',
    label: 'Nike Air Zoom Running Shoes',
    category: 'Fashion & Footwear',
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=400&q=80',
    description: 'Athletic breathable mesh road running sneakers with cushioned sole',
    targetProductQuery: 'Nike Pegasus road running shoe cushion comfort sole',
    detectedCues: ['Waffle outsole', 'Breathable mesh upper', 'Zoom Air cushioning', 'Athletic footwear'],
  },
  {
    id: 'sample-laptop',
    label: 'MacBook Air M3 Laptop',
    category: 'Laptops & Computing',
    thumbnail: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=400&q=80',
    description: 'Slim unibody aluminum laptop open on workspace',
    targetProductQuery: 'Apple MacBook Air M3 laptop battery silent retina',
    detectedCues: ['Anodized aluminum unibody', 'Trackpad & scissor keyboard', 'Retina display', 'Computing'],
  },
  {
    id: 'sample-watch',
    label: 'Apple Watch Series 9',
    category: 'Smart Wearables',
    thumbnail: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=400&q=80',
    description: 'Digital smartwatch with silicone sports band and OLED face',
    targetProductQuery: 'Apple Watch Series 9 GPS gesture sensor battery',
    detectedCues: ['Rectangular curved display', 'Silicone sports band', 'Heart rate sensor array', 'Wearable tech'],
  },
];

export const VOICE_COMMAND_PRESETS: VoiceCommandPreset[] = [
  {
    id: 'voice-kurti',
    command: 'Show positive reviews for pure cotton embroidered kurtis',
    intentDescription: 'Queries positive testimonials on breathable cotton fabric and embroidery workmanship',
    targetCategory: 'Fashion & Footwear',
    autoFilters: { sentiment: 'Positive', aspect: 'Fabric' },
  },
  {
    id: 'voice-shirt',
    command: 'Find reviews on Oxford cotton shirt collar and fit',
    intentDescription: 'Analyzes consumer feedback regarding structured collar durability and tailored fit',
    targetCategory: 'Fashion & Footwear',
    autoFilters: { aspect: 'Fabric' },
  },
  {
    id: 'voice-1',
    command: 'Find negative reviews about battery life',
    intentDescription: 'Searches negative sentiment reviews targeting battery drainage and charging longevity',
    targetCategory: 'All',
    autoFilters: { sentiment: 'Negative', aspect: 'Battery' },
  },
  {
    id: 'voice-2',
    command: 'Show 5 star reviews on Amazon for headphones',
    intentDescription: 'Filters verified 5-star customer reviews for audio and headphones on Amazon',
    targetCategory: 'Audio & Acoustics',
    autoFilters: { platform: 'Amazon', minRating: 5 },
  },
  {
    id: 'voice-3',
    command: 'Are there complaints about delivery packaging?',
    intentDescription: 'Surfaces consumer feedback concerning transit box damage, crushed packaging, or delays',
    targetCategory: 'All',
    autoFilters: { aspect: 'Packaging' },
  },
  {
    id: 'voice-4',
    command: 'Find reviews about sensitive skin irritation',
    intentDescription: 'Analyzes consumer skincare testimonials regarding redness, breakouts, and tolerance',
    targetCategory: 'Beauty & Skincare',
    autoFilters: { aspect: 'Skin' },
  },
  {
    id: 'voice-5',
    command: 'Show authentic verified reviews on Nykaa',
    intentDescription: 'Filters verified customer testimonials specifically on the Nykaa platform',
    targetCategory: 'All',
    autoFilters: { platform: 'Nykaa', verifiedOnly: true },
  },
  {
    id: 'voice-6',
    command: 'Search comfortable running shoes with good cushion',
    intentDescription: 'Queries positive athletic footwear reviews praising sole rebound and road comfort',
    targetCategory: 'Fashion & Footwear',
    autoFilters: { sentiment: 'Positive' },
  },
];
